# Generated by Django 4.0.3 on 2022-03-29 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(db_column='NOME_INSTITUICAO', max_length=50, null=True)),
                ('cnpj', models.CharField(db_column='CNPJ', max_length=14, null=True, validators=[django.core.validators.MinLengthValidator(14), django.core.validators.MaxLengthValidator(14)])),
                ('logradouro', models.CharField(db_column='LOGRADOURO', max_length=20, null=True)),
                ('numero', models.CharField(max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('complemento', models.CharField(db_column='COMPLEMENTO', max_length=20, null=True)),
                ('bairro', models.CharField(db_column='BAIRRO', max_length=20, null=True)),
                ('municipio', models.CharField(db_column='MUNICIPIO', max_length=20, null=True)),
                ('uf', models.CharField(choices=[('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], db_column='UF', max_length=2, null=True)),
                ('cep', models.CharField(db_column='CEP', max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)])),
                ('telefone', models.CharField(db_column='TELEFONE', max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(11)])),
                ('ano_fundacao', models.CharField(db_column='ANO_FUNDACAO', max_length=4, null=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(4)])),
                ('total_membros', models.PositiveIntegerField(db_column='TOTAL_MEMBROS', null=True)),
                ('nome_presidente_instituicao', models.CharField(db_column='NOME_PRESIDENTE_INSTITUICAO', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': 'PERFIL',
            },
        ),
    ]
